export const ACCESS_TOKEN = 'da_token';
export const MESSAGE_SUBJECT = 'New Message';
export const HTTP_RETRY_COUNT = 3;
export const HTTP_RETRY_DELAY = 5000;

export const HTTP_STATUS = {
  NO_CONNECTION: 0,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  METHOD_NOT_ALLOWED: 405,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
  BAD_GATEWAY: 502
};

export enum SERVER_ERRORS {
  NO_CONNECTION = 'NO_CONNECTION_ERROR',
  UNAUTHORIZED = 'AUTHORIZATION_ERROR',
  FORBIDDEN = 'FORBIDDEN_ERROR',
  INTERNAL_SERVER_ERROR = 'SYSTEM_ERROR'
}
